### ISSUE TITLE
Verify configuration only accepts one file

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/manage-github-apps#52]
It's not so clear from the documentation, but the `verify-config` command only accepts one file at a time.

It's be nice to support accepting one or more, i.e. `verify-config <file>...`.

This would play better with tools like `xargs`, without having to pass it a `-n 1` option.

**Comment by simonplend** [comment]
I think this is probably due to the [usage example in the README](https://github.com/Financial-Times/manage-github-apps#usage) being very limited - it only shows the available commands, not the options that each command makes available. If you run the `validate-config` command with the `--help` option, or with no arguments at all, you'll see the specific options available for that command:

```
$ npx github:financial-times/manage-github-apps validate-config --help
npx: installed 84 in 4.999s
manage-github-apps validate-config

Validate a JSON configuration against the manage-github-apps JSON schema

Options:
  --version     Show version number                                    [boolean]
  --help        Show help                                              [boolean]
  --config, -c  Path to JSON configuration (URL or local filepath)
                                                             [string] [required]
```

I've made a note in issue #26 to improve the usage section of the README.

I agree that it would be nice to add support for accepting multiple config paths for validation - I would happily welcome a pull request for this.
